# docker-compose build --no-cache
# docker-compose up -d

version: '3.8'

services:
  fhs-service:
    image: kerndatensatz-bildgebung-fhs-service:latest
    volumes:
      - type: bind
        source: ./temp
        target: /fhir-ig-publisher/temp
  #  build:
  #    dockerfile: Dockerfile