canonical: https://www.medizininformatik-initiative.de/fhir/ext/modul-bildgebung
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: mii-ig-bildgebung
name: MII_IG_Bildgebung
status: active
version: 2024.0.0
packageId: de.medizininformatikinitiative.kerndatensatz.bildgebung
copyrightYear: 2024+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  de.medizininformatikinitiative.kerndatensatz.meta: 1.0.3
  de.medizininformatikinitiative.kerndatensatz.prozedur: 2024.0.0
  de.medizininformatikinitiative.kerndatensatz.medikation: 2.0.0
  hl7.fhir.extensions.r5: 4.0.1
  fhir.dicom: 2024.1.20240120



# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
